from backend.northstar.endpoint_utils import (
    build_where,
    collect_fields,
    insert_payload,
    select_payload,
)


TRIP_CREATE_FIELDS = [
    "planner_id",
    "destination",
    "start_date",
    "end_date",
    "trip_type",
    "group_size",
    "trip_status",
    "trip_name",
    "city",
    "country",
    "region",
    "date_booked",
    "is_active",
]


def get_trips(validated):
    filters = build_where(
        validated["query"],
        equals={
            "planner_id": "t.planner_id",
            "destination": "t.destination",
            "trip_type": "t.trip_type",
            "trip_status": "t.trip_status",
            "is_active": "t.is_active",
        },
    )
    sql = """
        SELECT
            t.trip_id,
            t.planner_id,
            p.name AS planner_name,
            t.trip_name,
            t.destination,
            t.city,
            t.country,
            t.region,
            t.trip_type,
            t.start_date,
            t.end_date,
            t.group_size,
            t.trip_status,
            t.is_active,
            t.total_spent
        FROM Trip t
        JOIN Planner p ON p.planner_id = t.planner_id
    """
    return select_payload(sql, filters=filters, order_by="t.start_date, t.trip_id")


def post_trips(validated):
    values = collect_fields(validated["body"], TRIP_CREATE_FIELDS)
    values.setdefault("is_active", True)
    return insert_payload(
        "Trip",
        values,
        notes=[
            "Assumes trip identifiers will be generated by the database or a future service layer.",
        ],
    )
