from backend.northstar.endpoint_utils import (
    collect_fields,
    delete_payload,
    make_query,
    multi_query,
    select_payload,
    update_payload,
)


BOOKING_MUTABLE_FIELDS = [
    "promotion_id",
    "booking_date",
    "booking_status",
    "is_active",
]


def get_trip_bookings(validated):
    trip_id = validated["path"]["trip_id"]
    sql = """
        SELECT
            b.booking_id,
            b.trip_id,
            b.listing_id,
            l.service_category,
            l.description,
            l.price,
            b.vendor_id,
            v.vendor_name,
            b.promotion_id,
            p.title AS promotion_title,
            b.booking_date,
            b.booking_status,
            b.is_active
        FROM Booking b
        JOIN Listing l ON l.listing_id = b.listing_id
        JOIN Vendor v ON v.vendor_id = b.vendor_id
        LEFT JOIN Promotion p ON p.promotion_id = b.promotion_id
    """
    return select_payload(sql, filters=(["b.trip_id = %s"], [trip_id]), order_by="b.booking_date, b.booking_id")


def post_trip_bookings(validated):
    trip_id = validated["path"]["trip_id"]
    body = validated["body"]
    queries = [
        make_query(
            """
            INSERT INTO Booking (
                trip_id,
                listing_id,
                vendor_id,
                promotion_id,
                booking_date,
                booking_status,
                is_active
            )
            VALUES (%s, %s, (SELECT vendor_id FROM Listing WHERE listing_id = %s), %s, %s, %s, %s)
            """,
            [
                trip_id,
                body["listing_id"],
                body["listing_id"],
                body.get("promotion_id"),
                body.get("booking_date"),
                body.get("booking_status", "Proposed"),
                body.get("is_active", True),
            ],
            name="create_booking",
        )
    ]

    for traveler_id in body.get("traveler_ids", []):
        queries.append(
            make_query(
                """
                INSERT INTO Traveler_Booking (traveler_id, booking_id)
                VALUES (%s, LAST_INSERT_ID())
                """,
                [traveler_id],
                name=f"attach_traveler_{traveler_id}",
            )
        )

    return multi_query(
        queries,
        notes=[
            "Vendor assignment is derived from the selected listing.",
            "Traveler_Booking inserts assume the booking identifier will be generated by the database.",
        ],
    )


def put_trip_bookings(validated):
    trip_id = validated["path"]["trip_id"]
    queries = []
    for index, item in enumerate(validated["body"]["items"], start=1):
        queries.extend(_build_booking_update_queries(trip_id, item, index))
    return multi_query(queries)


def delete_trip_bookings(validated):
    trip_id = validated["path"]["trip_id"]
    queries = []
    for index, item in enumerate(validated["body"]["items"], start=1):
        queries.append(
            update_payload(
                "Booking",
                {"is_active": False},
                where_clause="trip_id = %s AND booking_id = %s",
                where_params=[trip_id, item["booking_id"]],
                notes=[f"Soft delete placeholder for bulk booking item {index}."],
            )
        )
    return multi_query(queries)


def _build_booking_update_queries(trip_id, item, index):
    booking_id = item["booking_id"]
    queries = []

    values = collect_fields(item, BOOKING_MUTABLE_FIELDS)
    if values:
        queries.append(
            update_payload(
                "Booking",
                values,
                where_clause="trip_id = %s AND booking_id = %s",
                where_params=[trip_id, booking_id],
                notes=[f"Bulk booking update item {index}."],
            )
        )

    if "traveler_ids" in item:
        queries.append(
            delete_payload(
                "Traveler_Booking",
                where_clause="booking_id = %s",
                where_params=[booking_id],
                notes=[f"Reset traveler associations for booking {booking_id}."],
            )
        )
        for traveler_id in item["traveler_ids"]:
            queries.append(
                make_query(
                    "INSERT INTO Traveler_Booking (traveler_id, booking_id) VALUES (%s, %s)",
                    [traveler_id, booking_id],
                    name=f"booking_{booking_id}_traveler_{traveler_id}",
                )
            )

    return queries
