INSERT INTO Traveler_Preference VALUES
(1, 'Window seat', 1),
(2, 'Direct flights', 1),
(3, 'Quiet lodging', 1),
(4, 'Northern lights tours', 1),
(5, 'Vegetarian meals', 1),
(6, 'Spa access', 9),
(7, 'Beach activities', 9),
(8, 'Wellness classes', 9),
(9, 'Museum visits', 2),
(10, 'Local restaurants', 2),
(11, 'Walking tours', 2),
(12, 'Boutique hotels', 2),
(13, 'Coastal views', 2),
(14, 'Cultural workshops', 3),
(15, 'Rail transfers', 3),
(16, 'Street food tours', 3),
(17, 'Guided temples', 3),
(18, 'Late checkout', 3),
(19, 'Private transfers', 3),
(20, 'Wildlife drives', 4),
(21, 'Photography stops', 4),
(22, 'All-inclusive lodging', 4),
(23, 'Family rooms', 4),
(24, 'Early departures', 4),
(25, 'Accessible rooms', 4),
(26, 'Local guides', 4),
(27, 'Outdoor dining', 4),
(28, 'Souvenir shopping', 4),
(29, 'Flexible itinerary', 4),
(30, 'Ski rentals', 5),
(31, 'Mountain views', 5),
(32, 'Beginner lessons', 5),
(33, 'Hot breakfast', 5),
(34, 'Rental car pickup', 6),
(35, 'Scenic routes', 6),
(36, 'Pet-friendly stays', 6),
(37, 'Hiking permits', 7),
(38, 'Gear rental', 7),
(39, 'Small group tours', 7),
(40, 'Altitude support', 7);
