INSERT INTO Listing_Amenity VALUES
(1, 'WiFi'),
(1, 'Breakfast'),
(2, 'Checked baggage'),
(2, 'In-flight meal'),
(3, 'Beach access'),
(3, 'Spa'),
(4, 'Parking'),
(4, 'Airport shuttle'),
(5, 'Local guide'),
(5, 'Museum passes'),
(6, 'GPS navigation'),
(6, 'Insurance included'),
(7, 'Climbing gear'),
(7, 'Safety briefing'),
(8, 'Wheelchair access'),
(8, 'Luggage storage'),
(9, 'Lunch included'),
(9, 'Private guide'),
(10, 'Seat selection'),
(10, 'Carry-on bag'),
(11, 'Onboard credit'),
(11, 'Balcony cabin'),
(12, 'Breakfast'),
(12, 'Fitness center'),
(13, 'Audio guide'),
(13, 'Walking route'),
(14, 'Equipment included'),
(14, 'Trail snacks'),
(15, 'Concierge'),
(15, 'Airport transfer'),
(16, 'Trail map'),
(16, 'Group discount'),
(17, 'Free guide'),
(17, 'Photo stops'),
(18, 'Unlimited rides'),
(18, 'Mobile ticket'),
(19, 'Budget fare'),
(19, 'Online check-in'),
(20, 'Hot drinks'),
(20, 'Thermal gear'),
(21, 'Pool'),
(21, 'Free breakfast'),
(22, 'Cultural guide'),
(22, 'Entry tickets'),
(23, 'Business center'),
(23, 'Corporate rate'),
(24, 'Boat transfer'),
(24, 'Snorkel gear'),
(25, 'Expedition guide'),
(25, 'Permit support'),
(26, 'Late checkout'),
(26, 'City shuttle'),
(27, 'All-inclusive'),
(27, 'VIP lounge'),
(28, 'Transit pass'),
(28, 'Route support'),
(29, 'Room upgrade'),
(29, 'Welcome drink'),
(30, 'Weekend discount'),
(30, '24/7 desk');
