from backend.northstar.routes import analytics_booking_trends  # noqa: F401
from backend.northstar.routes import analytics_data_quality_trips  # noqa: F401
from backend.northstar.routes import analytics_destinations  # noqa: F401
from backend.northstar.routes import analytics_spending  # noqa: F401
from backend.northstar.routes import analytics_vendors  # noqa: F401
from backend.northstar.routes import listing_amenities  # noqa: F401
from backend.northstar.routes import listing_detail  # noqa: F401
from backend.northstar.routes import listings  # noqa: F401
from backend.northstar.routes import notification_detail  # noqa: F401
from backend.northstar.routes import promotion_detail  # noqa: F401
from backend.northstar.routes import traveler_detail  # noqa: F401
from backend.northstar.routes import traveler_notifications  # noqa: F401
from backend.northstar.routes import travelers  # noqa: F401
from backend.northstar.routes import trip_booking_detail  # noqa: F401
from backend.northstar.routes import trip_bookings  # noqa: F401
from backend.northstar.routes import trip_budget  # noqa: F401
from backend.northstar.routes import trip_detail  # noqa: F401
from backend.northstar.routes import trip_itinerary  # noqa: F401
from backend.northstar.routes import trip_listing_votes  # noqa: F401
from backend.northstar.routes import trip_notifications  # noqa: F401
from backend.northstar.routes import trip_preferences  # noqa: F401
from backend.northstar.routes import trip_traveler_detail  # noqa: F401
from backend.northstar.routes import trip_traveler_preferences  # noqa: F401
from backend.northstar.routes import trip_traveler_votes  # noqa: F401
from backend.northstar.routes import trip_travelers  # noqa: F401
from backend.northstar.routes import trip_votes  # noqa: F401
from backend.northstar.routes import trips  # noqa: F401
from backend.northstar.routes import vendor_detail  # noqa: F401
from backend.northstar.routes import vendor_listings  # noqa: F401
from backend.northstar.routes import vendor_promotions  # noqa: F401
from backend.northstar.routes import vendors  # noqa: F401
